name: Benchmarks
on:
  pull_request_target:
    branches: [ main ]
permissions:
  pull-requests: write

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          julia-version: '1.10'
          bench-on: ${{ github.event.pull_request.head.sha }}
